/*
 Masonry PACKAGED v4.1.1
 Cascading grid layout library
 http://masonry.desandro.com
 MIT License
 by David DeSandro
*/
!function(d,c){"function"==typeof define&&define.amd?define("jquery-bridget/jquery-bridget",["jquery"],function(g){return c(d,g)}):"object"==typeof module&&module.exports?module.exports=c(d,require("jquery")):d.jQueryBridget=c(d,d.jQuery)}(window,function(d,c){function g(f,g,p){function k(e,l,h){var m,b="$()."+f+'("'+l+'")';return e.each(function(e,a){var r=p.data(a,f);if(!r)return void q(f+" not initialized. Cannot call methods, i.e. "+b);var k=r[l];if(!k||"_"==l.charAt(0))return void q(b+" is not a valid method");
r=k.apply(r,h);m=void 0===m?r:m}),void 0!==m?m:e}function l(e,l){e.each(function(h,e){var m=p.data(e,f);m?(m.option(l),m._init()):(m=new g(e,l),p.data(e,f,m))})}(p=p||c||d.jQuery)&&(g.prototype.option||(g.prototype.option=function(e){p.isPlainObject(e)&&(this.options=p.extend(!0,this.options,e))}),p.fn[f]=function(e){if("string"==typeof e){var a=b.call(arguments,1);return k(this,e,a)}return l(this,e),this},a(p))}function a(b){!b||b&&b.bridget||(b.bridget=g)}var b=Array.prototype.slice,f=d.console,
q="undefined"==typeof f?function(){}:function(b){f.error(b)};return a(c||d.jQuery),g});
(function(d,c){"function"==typeof define&&define.amd?define("ev-emitter/ev-emitter",c):"object"==typeof module&&module.exports?module.exports=c():d.EvEmitter=c()})("undefined"!=typeof window?window:this,function(){function d(){}var c=d.prototype;return c.on=function(g,a){if(g&&a){var b=this._events=this._events||{},b=b[g]=b[g]||[];return-1==b.indexOf(a)&&b.push(a),this}},c.once=function(g,a){if(g&&a){this.on(g,a);var b=this._onceEvents=this._onceEvents||{};return(b[g]=b[g]||{})[a]=!0,this}},c.off=
function(g,a){var b=this._events&&this._events[g];if(b&&b.length){var f=b.indexOf(a);return-1!=f&&b.splice(f,1),this}},c.emitEvent=function(g,a){var b=this._events&&this._events[g];if(b&&b.length){var f=0,d=b[f];a=a||[];for(var k=this._onceEvents&&this._onceEvents[g];d;){var c=k&&k[d];c&&(this.off(g,d),delete k[d]);d.apply(this,a);f+=c?0:1;d=b[f]}return this}},d});
(function(d,c){"function"==typeof define&&define.amd?define("get-size/get-size",[],function(){return c()}):"object"==typeof module&&module.exports?module.exports=c():d.getSize=c()})(window,function(){function d(b){var a=parseFloat(b);return-1==b.indexOf("%")&&!isNaN(a)&&a}function c(){}function g(b){b=getComputedStyle(b);return b||f("Style returned "+b+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1"),b}function a(f){if(!n){n=!0;var c=document.createElement("div");
c.style.width="200px";c.style.padding="1px 2px 3px 4px";c.style.borderStyle="solid";c.style.borderWidth="1px 2px 3px 4px";c.style.boxSizing="border-box";var l=document.body||document.documentElement;l.appendChild(c);var e=g(c);a.isBoxSizeOuter=b=200==d(e.width);l.removeChild(c)}if("string"==typeof f&&(f=document.querySelector(f)),f&&"object"==typeof f&&f.nodeType){l=g(f);if("none"==l.display){c={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0};for(l=0;k>l;l++)c[q[l]]=0;return c}c=
{};c.width=f.offsetWidth;c.height=f.offsetHeight;f=c.isBorderBox="border-box"==l.boxSizing;for(e=0;k>e;e++){var t=q[e],h=parseFloat(l[t]);c[t]=isNaN(h)?0:h}var e=c.paddingLeft+c.paddingRight,t=c.paddingTop+c.paddingBottom,h=c.marginLeft+c.marginRight,m=c.marginTop+c.marginBottom,r=c.borderLeftWidth+c.borderRightWidth,v=c.borderTopWidth+c.borderBottomWidth;f=f&&b;var p=d(l.width);!1!==p&&(c.width=p+(f?0:e+r));l=d(l.height);return!1!==l&&(c.height=l+(f?0:t+v)),c.innerWidth=c.width-(e+r),c.innerHeight=
c.height-(t+v),c.outerWidth=c.width+h,c.outerHeight=c.height+m,c}}var b,f="undefined"==typeof console?c:function(b){console.error(b)},q="paddingLeft paddingRight paddingTop paddingBottom marginLeft marginRight marginTop marginBottom borderLeftWidth borderRightWidth borderTopWidth borderBottomWidth".split(" "),k=q.length,n=!1;return a});
(function(d,c){"function"==typeof define&&define.amd?define("desandro-matches-selector/matches-selector",c):"object"==typeof module&&module.exports?module.exports=c():d.matchesSelector=c()})(window,function(){var d=function(){var c=Element.prototype;if(c.matches)return"matches";if(c.matchesSelector)return"matchesSelector";for(var d=["webkit","moz","ms","o"],a=0;a<d.length;a++){var b=d[a]+"MatchesSelector";if(c[b])return b}}();return function(c,g){return c[d](g)}});
(function(d,c){"function"==typeof define&&define.amd?define("fizzy-ui-utils/utils",["desandro-matches-selector/matches-selector"],function(g){return c(d,g)}):"object"==typeof module&&module.exports?module.exports=c(d,require("desandro-matches-selector")):d.fizzyUIUtils=c(d,d.matchesSelector)})(window,function(d,c){var g={extend:function(b,f){for(var a in f)b[a]=f[a];return b},modulo:function(b,a){return(b%a+a)%a},makeArray:function(b){var a=[];if(Array.isArray(b))a=b;else if(b&&"number"==typeof b.length)for(var c=
0;c<b.length;c++)a.push(b[c]);else a.push(b);return a},removeFrom:function(b,a){var c=b.indexOf(a);-1!=c&&b.splice(c,1)},getParent:function(b,a){for(;b!=document.body;)if(b=b.parentNode,c(b,a))return b},getQueryElement:function(b){return"string"==typeof b?document.querySelector(b):b},handleEvent:function(b){var a="on"+b.type;this[a]&&this[a](b)},filterFindElements:function(b,a){b=g.makeArray(b);var f=[];return b.forEach(function(b){if(b instanceof HTMLElement){if(!a)return void f.push(b);c(b,a)&&
f.push(b);b=b.querySelectorAll(a);for(var d=0;d<b.length;d++)f.push(b[d])}}),f},debounceMethod:function(b,a,c){var f=b.prototype[a],d=a+"Timeout";b.prototype[a]=function(){var b=this[d];b&&clearTimeout(b);var a=arguments,l=this;this[d]=setTimeout(function(){f.apply(l,a);delete l[d]},c||100)}},docReady:function(b){var a=document.readyState;"complete"==a||"interactive"==a?b():document.addEventListener("DOMContentLoaded",b)},toDashed:function(a){return a.replace(/(.)([A-Z])/g,function(a,b,c){return b+
"-"+c}).toLowerCase()}},a=d.console;return g.htmlInit=function(b,c){g.docReady(function(){var f=g.toDashed(c),k="data-"+f,n=document.querySelectorAll("["+k+"]"),f=document.querySelectorAll(".js-"+f),n=g.makeArray(n).concat(g.makeArray(f)),p=k+"-options",u=d.jQuery;n.forEach(function(l){var e,f=l.getAttribute(k)||l.getAttribute(p);try{e=f&&JSON.parse(f)}catch(h){return void(a&&a.error("Error parsing "+k+" on "+l.className+": "+h))}e=new b(l,e);u&&u.data(l,c,e)})})},g});
(function(d,c){"function"==typeof define&&define.amd?define("outlayer/item",["ev-emitter/ev-emitter","get-size/get-size"],c):"object"==typeof module&&module.exports?module.exports=c(require("ev-emitter"),require("get-size")):(d.Outlayer={},d.Outlayer.Item=c(d.EvEmitter,d.getSize))})(window,function(d,c){function g(a,e){a&&(this.element=a,this.layout=e,this.position={x:0,y:0},this._create())}var a=document.documentElement.style,b="string"==typeof a.transition?"transition":"WebkitTransition",a="string"==
typeof a.transform?"transform":"WebkitTransform",f={WebkitTransition:"webkitTransitionEnd",transition:"transitionend"}[b],q={transform:a,transition:b,transitionDuration:b+"Duration",transitionProperty:b+"Property",transitionDelay:b+"Delay"},k=g.prototype=Object.create(d.prototype);k.constructor=g;k._create=function(){this._transn={ingProperties:{},clean:{},onEnd:{}};this.css({position:"absolute"})};k.handleEvent=function(a){var e="on"+a.type;this[e]&&this[e](a)};k.getSize=function(){this.size=c(this.element)};
k.css=function(a){var e=this.element.style,b;for(b in a)e[q[b]||b]=a[b]};k.getPosition=function(){var a=getComputedStyle(this.element),b=this.layout._getOption("originLeft"),c=this.layout._getOption("originTop"),h=a[b?"left":"right"],m=a[c?"top":"bottom"],a=this.layout.size,h=-1!=h.indexOf("%")?parseFloat(h)/100*a.width:parseInt(h,10),m=-1!=m.indexOf("%")?parseFloat(m)/100*a.height:parseInt(m,10),h=isNaN(h)?0:h,m=isNaN(m)?0:m,h=h-(b?a.paddingLeft:a.paddingRight),m=m-(c?a.paddingTop:a.paddingBottom);
this.position.x=h;this.position.y=m};k.layoutPosition=function(){var a=this.layout.size,b={},c=this.layout._getOption("originLeft"),h=this.layout._getOption("originTop"),m=c?"right":"left";b[c?"left":"right"]=this.getXValue(this.position.x+a[c?"paddingLeft":"paddingRight"]);b[m]="";c=h?"bottom":"top";b[h?"top":"bottom"]=this.getYValue(this.position.y+a[h?"paddingTop":"paddingBottom"]);b[c]="";this.css(b);this.emitEvent("layout",[this])};k.getXValue=function(a){var b=this.layout._getOption("horizontal");
return this.layout.options.percentPosition&&!b?a/this.layout.size.width*100+"%":a+"px"};k.getYValue=function(a){var b=this.layout._getOption("horizontal");return this.layout.options.percentPosition&&b?a/this.layout.size.height*100+"%":a+"px"};k._transitionTo=function(a,b){this.getPosition();var e=this.position.x,h=this.position.y,c=parseInt(a,10),l=parseInt(b,10),c=c===this.position.x&&l===this.position.y;if(this.setPosition(a,b),c&&!this.isTransitioning)return void this.layoutPosition();c={};c.transform=
this.getTranslate(a-e,b-h);this.transition({to:c,onTransitionEnd:{transform:this.layoutPosition},isCleaning:!0})};k.getTranslate=function(a,b){var c=this.layout._getOption("originLeft"),h=this.layout._getOption("originTop");return a=c?a:-a,b=h?b:-b,"translate3d("+a+"px, "+b+"px, 0)"};k.goTo=function(a,b){this.setPosition(a,b);this.layoutPosition()};k.moveTo=k._transitionTo;k.setPosition=function(a,b){this.position.x=parseInt(a,10);this.position.y=parseInt(b,10)};k._nonTransition=function(a){this.css(a.to);
a.isCleaning&&this._removeStyles(a.to);for(var b in a.onTransitionEnd)a.onTransitionEnd[b].call(this)};k.transition=function(a){if(!parseFloat(this.layout.options.transitionDuration))return void this._nonTransition(a);var b=this._transn,c;for(c in a.onTransitionEnd)b.onEnd[c]=a.onTransitionEnd[c];for(c in a.to)b.ingProperties[c]=!0,a.isCleaning&&(b.clean[c]=!0);a.from&&this.css(a.from);this.enableTransition(a.to);this.css(a.to);this.isTransitioning=!0};var n="opacity,"+function(a){return a.replace(/([A-Z])/g,
function(a){return"-"+a.toLowerCase()})}(a);k.enableTransition=function(){if(!this.isTransitioning){var a=this.layout.options.transitionDuration;this.css({transitionProperty:n,transitionDuration:"number"==typeof a?a+"ms":a,transitionDelay:this.staggerDelay||0});this.element.addEventListener(f,this,!1)}};k.onwebkitTransitionEnd=function(a){this.ontransitionend(a)};k.onotransitionend=function(a){this.ontransitionend(a)};var p={"-webkit-transform":"transform"};k.ontransitionend=function(a){if(a.target===
this.element){var b=this._transn,c=p[a.propertyName]||a.propertyName;delete b.ingProperties[c];var h;a:{h=b.ingProperties;for(var m in h){h=!1;break a}h=!0}if(h&&this.disableTransition(),c in b.clean&&(this.element.style[a.propertyName]="",delete b.clean[c]),c in b.onEnd)b.onEnd[c].call(this),delete b.onEnd[c];this.emitEvent("transitionEnd",[this])}};k.disableTransition=function(){this.removeTransitionStyles();this.element.removeEventListener(f,this,!1);this.isTransitioning=!1};k._removeStyles=function(a){var b=
{},c;for(c in a)b[c]="";this.css(b)};var u={transitionProperty:"",transitionDuration:"",transitionDelay:""};return k.removeTransitionStyles=function(){this.css(u)},k.stagger=function(a){a=isNaN(a)?0:a;this.staggerDelay=a+"ms"},k.removeElem=function(){this.element.parentNode.removeChild(this.element);this.css({display:""});this.emitEvent("remove",[this])},k.remove=function(){return b&&parseFloat(this.layout.options.transitionDuration)?(this.once("transitionEnd",function(){this.removeElem()}),void this.hide()):
void this.removeElem()},k.reveal=function(){delete this.isHidden;this.css({display:""});var a=this.layout.options,b={},c=this.getHideRevealTransitionEndProperty("visibleStyle");b[c]=this.onRevealTransitionEnd;this.transition({from:a.hiddenStyle,to:a.visibleStyle,isCleaning:!0,onTransitionEnd:b})},k.onRevealTransitionEnd=function(){this.isHidden||this.emitEvent("reveal")},k.getHideRevealTransitionEndProperty=function(a){a=this.layout.options[a];if(a.opacity)return"opacity";for(var b in a)return b},
k.hide=function(){this.isHidden=!0;this.css({display:""});var a=this.layout.options,b={},c=this.getHideRevealTransitionEndProperty("hiddenStyle");b[c]=this.onHideTransitionEnd;this.transition({from:a.visibleStyle,to:a.hiddenStyle,isCleaning:!0,onTransitionEnd:b})},k.onHideTransitionEnd=function(){this.isHidden&&(this.css({display:"none"}),this.emitEvent("hide"))},k.destroy=function(){this.css({position:"",left:"",right:"",top:"",bottom:"",transition:"",transform:""})},g});
(function(d,c){"function"==typeof define&&define.amd?define("outlayer/outlayer",["ev-emitter/ev-emitter","get-size/get-size","fizzy-ui-utils/utils","./item"],function(g,a,b,f){return c(d,g,a,b,f)}):"object"==typeof module&&module.exports?module.exports=c(d,require("ev-emitter"),require("get-size"),require("fizzy-ui-utils"),require("./item")):d.Outlayer=c(d,d.EvEmitter,d.getSize,d.fizzyUIUtils,d.Outlayer.Item)})(window,function(d,c,g,a,b){function f(h,b){var c=a.getQueryElement(h);if(!c)return void(k&&
k.error("Bad element for "+this.constructor.namespace+": "+(c||h)));this.element=c;n&&(this.$element=n(this.element));this.options=a.extend({},this.constructor.defaults);this.option(b);c=++u;this.element.outlayerGUID=c;l[c]=this;this._create();this._getOption("initLayout")&&this.layout()}function q(a){function h(){a.apply(this,arguments)}return h.prototype=Object.create(a.prototype),h.prototype.constructor=h,h}var k=d.console,n=d.jQuery,p=function(){},u=0,l={};f.namespace="outlayer";f.Item=b;f.defaults=
{containerStyle:{position:"relative"},initLayout:!0,originLeft:!0,originTop:!0,resize:!0,resizeContainer:!0,transitionDuration:"0.4s",hiddenStyle:{opacity:0,transform:"scale(0.001)"},visibleStyle:{opacity:1,transform:"scale(1)"}};var e=f.prototype;a.extend(e,c.prototype);e.option=function(h){a.extend(this.options,h)};e._getOption=function(a){var h=this.constructor.compatOptions[a];return h&&void 0!==this.options[h]?this.options[h]:this.options[a]};f.compatOptions={initLayout:"isInitLayout",horizontal:"isHorizontal",
layoutInstant:"isLayoutInstant",originLeft:"isOriginLeft",originTop:"isOriginTop",resize:"isResizeBound",resizeContainer:"isResizingContainer"};e._create=function(){this.reloadItems();this.stamps=[];this.stamp(this.options.stamp);a.extend(this.element.style,this.options.containerStyle);this._getOption("resize")&&this.bindResize()};e.reloadItems=function(){this.items=this._itemize(this.element.children)};e._itemize=function(a){a=this._filterFindItemElements(a);for(var h=this.constructor.Item,b=[],
c=0;c<a.length;c++){var e=new h(a[c],this);b.push(e)}return b};e._filterFindItemElements=function(h){return a.filterFindElements(h,this.options.itemSelector)};e.getItemElements=function(){return this.items.map(function(a){return a.element})};e.layout=function(){this._resetLayout();this._manageStamps();var a=this._getOption("layoutInstant");this.layoutItems(this.items,void 0!==a?a:!this._isLayoutInited);this._isLayoutInited=!0};e._init=e.layout;e._resetLayout=function(){this.getSize()};e.getSize=function(){this.size=
g(this.element)};e._getMeasurement=function(a,b){var h,c=this.options[a];c?("string"==typeof c?h=this.element.querySelector(c):c instanceof HTMLElement&&(h=c),this[a]=h?g(h)[b]:c):this[a]=0};e.layoutItems=function(a,b){a=this._getItemsForLayout(a);this._layoutItems(a,b);this._postLayout()};e._getItemsForLayout=function(a){return a.filter(function(a){return!a.isIgnored})};e._layoutItems=function(a,b){if(this._emitCompleteOnItems("layout",a),a&&a.length){var h=[];a.forEach(function(a){var c=this._getItemLayoutPosition(a);
c.item=a;c.isInstant=b||a.isLayoutInstant;h.push(c)},this);this._processLayoutQueue(h)}};e._getItemLayoutPosition=function(){return{x:0,y:0}};e._processLayoutQueue=function(a){this.updateStagger();a.forEach(function(a,b){this._positionItem(a.item,a.x,a.y,a.isInstant,b)},this)};e.updateStagger=function(){var a=this.options.stagger;if(null===a||void 0===a)a=void(this.stagger=0);else{if("number"!=typeof a){var b=a.match(/(^\d*\.?\d*)(\w*)/),a=b&&b[1],b=b&&b[2];a.length?(a=parseFloat(a),a*=t[b]||1):a=
0}a=(this.stagger=a,this.stagger)}return a};e._positionItem=function(a,b,c,e,f){e?a.goTo(b,c):(a.stagger(f*this.stagger),a.moveTo(b,c))};e._postLayout=function(){this.resizeContainer()};e.resizeContainer=function(){if(this._getOption("resizeContainer")){var a=this._getContainerSize();a&&(this._setContainerMeasure(a.width,!0),this._setContainerMeasure(a.height,!1))}};e._getContainerSize=p;e._setContainerMeasure=function(a,b){if(void 0!==a){var c=this.size;c.isBorderBox&&(a+=b?c.paddingLeft+c.paddingRight+
c.borderLeftWidth+c.borderRightWidth:c.paddingBottom+c.paddingTop+c.borderTopWidth+c.borderBottomWidth);a=Math.max(a,0);this.element.style[b?"width":"height"]=a+"px"}};e._emitCompleteOnItems=function(a,b){function c(){e.dispatchEvent(a+"Complete",null,[b])}function h(){d++;d==f&&c()}var e=this,f=b.length;if(!b||!f)return void c();var d=0;b.forEach(function(b){b.once(a,h)})};e.dispatchEvent=function(a,b,c){var h=b?[b].concat(c):c;if(this.emitEvent(a,h),n)(this.$element=this.$element||n(this.element),
b)?(b=n.Event(b),b.type=a,this.$element.trigger(b,c)):this.$element.trigger(a,c)};e.ignore=function(a){(a=this.getItem(a))&&(a.isIgnored=!0)};e.unignore=function(a){(a=this.getItem(a))&&delete a.isIgnored};e.stamp=function(a){(a=this._find(a))&&(this.stamps=this.stamps.concat(a),a.forEach(this.ignore,this))};e.unstamp=function(b){(b=this._find(b))&&b.forEach(function(b){a.removeFrom(this.stamps,b);this.unignore(b)},this)};e._find=function(b){return b?("string"==typeof b&&(b=this.element.querySelectorAll(b)),
a.makeArray(b)):void 0};e._manageStamps=function(){this.stamps&&this.stamps.length&&(this._getBoundingRect(),this.stamps.forEach(this._manageStamp,this))};e._getBoundingRect=function(){var a=this.element.getBoundingClientRect(),b=this.size;this._boundingRect={left:a.left+b.paddingLeft+b.borderLeftWidth,top:a.top+b.paddingTop+b.borderTopWidth,right:a.right-(b.paddingRight+b.borderRightWidth),bottom:a.bottom-(b.paddingBottom+b.borderBottomWidth)}};e._manageStamp=p;e._getElementOffset=function(a){var b=
a.getBoundingClientRect(),c=this._boundingRect;a=g(a);return{left:b.left-c.left-a.marginLeft,top:b.top-c.top-a.marginTop,right:c.right-b.right-a.marginRight,bottom:c.bottom-b.bottom-a.marginBottom}};e.handleEvent=a.handleEvent;e.bindResize=function(){d.addEventListener("resize",this);this.isResizeBound=!0};e.unbindResize=function(){d.removeEventListener("resize",this);this.isResizeBound=!1};e.onresize=function(){this.resize()};a.debounceMethod(f,"onresize",100);e.resize=function(){this.isResizeBound&&
this.needsResizeLayout()&&this.layout()};e.needsResizeLayout=function(){var a=g(this.element);return this.size&&a&&a.innerWidth!==this.size.innerWidth};e.addItems=function(a){a=this._itemize(a);return a.length&&(this.items=this.items.concat(a)),a};e.appended=function(a){a=this.addItems(a);a.length&&(this.layoutItems(a,!0),this.reveal(a))};e.prepended=function(a){a=this._itemize(a);if(a.length){var b=this.items.slice(0);this.items=a.concat(b);this._resetLayout();this._manageStamps();this.layoutItems(a,
!0);this.reveal(a);this.layoutItems(b)}};e.reveal=function(a){if(this._emitCompleteOnItems("reveal",a),a&&a.length){var b=this.updateStagger();a.forEach(function(a,c){a.stagger(c*b);a.reveal()})}};e.hide=function(a){if(this._emitCompleteOnItems("hide",a),a&&a.length){var b=this.updateStagger();a.forEach(function(a,c){a.stagger(c*b);a.hide()})}};e.revealItemElements=function(a){a=this.getItems(a);this.reveal(a)};e.hideItemElements=function(a){a=this.getItems(a);this.hide(a)};e.getItem=function(a){for(var b=
0;b<this.items.length;b++){var c=this.items[b];if(c.element==a)return c}};e.getItems=function(b){b=a.makeArray(b);var c=[];return b.forEach(function(a){(a=this.getItem(a))&&c.push(a)},this),c};e.remove=function(b){b=this.getItems(b);this._emitCompleteOnItems("remove",b);b&&b.length&&b.forEach(function(b){b.remove();a.removeFrom(this.items,b)},this)};e.destroy=function(){var a=this.element.style;a.height="";a.position="";a.width="";this.items.forEach(function(a){a.destroy()});this.unbindResize();delete l[this.element.outlayerGUID];
delete this.element.outlayerGUID;n&&n.removeData(this.element,this.constructor.namespace)};f.data=function(b){return(b=(b=a.getQueryElement(b))&&b.outlayerGUID)&&l[b]};f.create=function(c,e){var d=q(f);return d.defaults=a.extend({},f.defaults),a.extend(d.defaults,e),d.compatOptions=a.extend({},f.compatOptions),d.namespace=c,d.data=f.data,d.Item=q(b),a.htmlInit(d,c),n&&n.bridget&&n.bridget(c,d),d};var t={ms:1,s:1E3};return f.Item=b,f});
(function(d,c){"function"==typeof define&&define.amd?define(["outlayer/outlayer","get-size/get-size"],c):"object"==typeof module&&module.exports?module.exports=c(require("outlayer"),require("get-size")):d.Masonry=c(d.Outlayer,d.getSize)})(window,function(d,c){var g=d.create("masonry");return g.compatOptions.fitWidth="isFitWidth",g.prototype._resetLayout=function(){this.getSize();this._getMeasurement("columnWidth","outerWidth");this._getMeasurement("gutter","outerWidth");this.measureColumns();this.colYs=
[];for(var a=0;a<this.cols;a++)this.colYs.push(0);this.maxY=0},g.prototype.measureColumns=function(){if(this.getContainerWidth(),!this.columnWidth){var a=this.items[0];this.columnWidth=(a=a&&a.element)&&c(a).outerWidth||this.containerWidth}var a=this.columnWidth+=this.gutter,b=this.containerWidth+this.gutter,f=a-b%a,a=Math[f&&1>f?"round":"floor"](b/a);this.cols=Math.max(a,1)},g.prototype.getContainerWidth=function(){var a=this._getOption("fitWidth")?this.element.parentNode:this.element;this.containerWidth=
(a=c(a))&&a.innerWidth},g.prototype._getItemLayoutPosition=function(a){a.getSize();var b=a.size.outerWidth%this.columnWidth,b=Math[b&&1>b?"round":"ceil"](a.size.outerWidth/this.columnWidth),b=Math.min(b,this.cols),c=this._getColGroup(b),d=Math.min.apply(Math,c),b=c.indexOf(d),g={x:this.columnWidth*b,y:d};a=d+a.size.outerHeight;c=this.cols+1-c.length;for(d=0;c>d;d++)this.colYs[b+d]=a;return g},g.prototype._getColGroup=function(a){if(2>a)return this.colYs;for(var b=[],c=this.cols+1-a,d=0;c>d;d++){var g=
this.colYs.slice(d,d+a);b[d]=Math.max.apply(Math,g)}return b},g.prototype._manageStamp=function(a){var b=c(a),d=this._getElementOffset(a);a=this._getOption("originLeft")?d.left:d.right;var g=a+b.outerWidth,k=Math.floor(a/this.columnWidth),k=Math.max(0,k);a=Math.floor(g/this.columnWidth);a-=g%this.columnWidth?0:1;a=Math.min(this.cols-1,a);b=(this._getOption("originTop")?d.top:d.bottom)+b.outerHeight;for(d=k;a>=d;d++)this.colYs[d]=Math.max(b,this.colYs[d])},g.prototype._getContainerSize=function(){this.maxY=
Math.max.apply(Math,this.colYs);var a={height:this.maxY};return this._getOption("fitWidth")&&(a.width=this._getContainerFitWidth()),a},g.prototype._getContainerFitWidth=function(){for(var a=0,b=this.cols;--b&&0===this.colYs[b];)a++;return(this.cols-a)*this.columnWidth-this.gutter},g.prototype.needsResizeLayout=function(){var a=this.containerWidth;return this.getContainerWidth(),a!=this.containerWidth},g});